import * as THREE from './vendor/three.module.min.js';
import { AuthoredAssets, AUTHORED_ASSETS } from './authored-assets.js?v=20260920-download68';
// One retained GPU renderer, cached indexed meshes, smooth normals and pooled objects.
const surface=document.createElement('canvas');
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas:surface,alpha:true,antialias:true,powerPreference:'high-performance',premultipliedAlpha:true});}catch(error){console.warn('WebGL unavailable; using compatibility renderer.',error)}
if(renderer){
 surface.addEventListener('webglcontextlost',event=>{event.preventDefault();window.dispatchEvent(new CustomEvent('game-render-error',{detail:new Error('The graphics context was lost.')}))});
 renderer.setSize(1440,760,false);renderer.setPixelRatio(1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.setClearColor(0x000000,0);
 const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-720,720,380,-380,1,4000);camera.position.z=1200;
 scene.add(new THREE.HemisphereLight(0xb7e9ff,0x25213d,2));
 const key=new THREE.DirectionalLight(0xffe6c4,3.4);key.position.set(-400,500,700);scene.add(key);
 const rim=new THREE.DirectionalLight(0x65cfff,2.8);rim.position.set(400,-100,-400);scene.add(rim);
 const fill=new THREE.DirectionalLight(0xbe88ff,.7);fill.position.set(500,-300,600);scene.add(fill);
 let bossAtlasTexture=null; // Legacy artwork loads only when a compatibility model requests it.
 const rockTexture=new THREE.TextureLoader().load('assets/asteroid-stone-v2.webp');rockTexture.colorSpace=THREE.SRGBColorSpace;rockTexture.wrapS=rockTexture.wrapT=THREE.RepeatWrapping;rockTexture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
 const alienTextures={};for(const [name,file] of Object.entries({chitin:'alien-chitin-v3.webp',flesh:'alien-flesh-v3.webp'})){const t=new THREE.TextureLoader().load('assets/'+file);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());alienTextures[name]=t;}
 function smoothNormals(g,groups){g.computeVertexNormals();const n=g.attributes.normal.array;for(const group of groups){let x=0,y=0,z=0;for(const i of group){x+=n[i*3];y+=n[i*3+1];z+=n[i*3+2];}const len=Math.hypot(x,y,z)||1;for(const i of group){n[i*3]=x/len;n[i*3+1]=y/len;n[i*3+2]=z/len;}}g.attributes.normal.needsUpdate=true;}
 const geoCache=new Map(),slots=[];let renderFrame=0,disposedGeometry=0;let used=0,batch=0,frames=0,peakTriangles=0,pending=0,frameDrawCalls=0,frameTriangles=0,pendingStart=0,frameCompositePixels=0,framePasses=0;
 let clipLeft=1440,clipTop=760,clipRight=0,clipBottom=0;
 const boundCenter=new THREE.Vector3();
 function resetClip(){clipLeft=1440;clipTop=760;clipRight=clipBottom=0;}
 function includeDrawBounds(data,faces,matrix){
  // CPU-final meshes may opt into bounds refreshed alongside vertex uploads.
  // Unknown/GPU-deformed motion retains its conservative full viewport.
  if(faces.dynamic&&(!faces.cpuBounds||!data.motionBounds)){clipLeft=clipTop=0;clipRight=1440;clipBottom=760;return true;}
  if(faces.cpuBounds&&data.motionBounds){
   const q=data.motionBounds,e=matrix.elements;boundCenter.set(q.cx,q.cy,q.cz).applyMatrix4(matrix);
   const rx=Math.abs(e[0])*q.hx+Math.abs(e[4])*q.hy+Math.abs(e[8])*q.hz+3,ry=Math.abs(e[1])*q.hx+Math.abs(e[5])*q.hy+Math.abs(e[9])*q.hz+3,x=720+boundCenter.x,y=380-boundCenter.y;
   if(x+rx<0||x-rx>1440||y+ry<0||y-ry>760)return false;
   clipLeft=Math.min(clipLeft,Math.max(0,Math.floor(x-rx)));clipTop=Math.min(clipTop,Math.max(0,Math.floor(y-ry)));clipRight=Math.max(clipRight,Math.min(1440,Math.ceil(x+rx)));clipBottom=Math.max(clipBottom,Math.min(760,Math.ceil(y+ry)));return true;
  }
  const sphere=data.geometry.boundingSphere,e=matrix.elements;boundCenter.copy(sphere.center).applyMatrix4(matrix);
  const rx=sphere.radius*Math.hypot(e[0],e[4],e[8])+3,ry=sphere.radius*Math.hypot(e[1],e[5],e[9])+3,x=720+boundCenter.x,y=380-boundCenter.y;
  if(x+rx<0||x-rx>1440||y+ry<0||y-ry>760)return false;
  clipLeft=Math.min(clipLeft,Math.max(0,Math.floor(x-rx)));clipTop=Math.min(clipTop,Math.max(0,Math.floor(y-ry)));clipRight=Math.max(clipRight,Math.min(1440,Math.ceil(x+rx)));clipBottom=Math.max(clipBottom,Math.min(760,Math.ceil(y+ry)));return true;
 }
 function makeTexture(organic){const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const c=canvas.getContext('2d'),data=c.createImageData(128,128);for(let y=0;y<128;y++)for(let x=0;x<128;x++){const hash=((x*73856093)^(y*19349663))>>>0,grain=(hash%37)-18;const groove=organic?(Math.sin(x*.23+Math.sin(y*.14)*2)*Math.cos(y*.31)*18+(hash%17===0?-48:0)):(x%32<2||y%48<2?-35:0);const value=128+grain*.35+groove;const k=(y*128+x)*4;data.data[k]=data.data[k+1]=data.data[k+2]=value;data.data[k+3]=255}c.putImageData(data,0,0);const t=new THREE.CanvasTexture(canvas);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());return t}
 const metalTexture=makeTexture(false),skinTexture=makeTexture(true);
 // One retained finish for painted machinery: fine abrasion and broad soot
 // mottling enrich the hull without repeating a prominent square panel image.
 const industrialCanvas=document.createElement('canvas');industrialCanvas.width=industrialCanvas.height=256;const industrialBrush=industrialCanvas.getContext('2d'),industrialData=industrialBrush.createImageData(256,256);
 for(let y=0;y<256;y++)for(let x=0;x<256;x++){const hash=((x*73856093)^(y*19349663))>>>0,grain=(hash%23)-11,soot=Math.pow(Math.max(0,Math.sin(x*.024+Math.sin(y*.043)*1.3)*Math.cos(y*.029-x*.012)),2),scratch=hash%317===0?25:0,value=232+grain*.6-soot*30-scratch,k=(y*256+x)*4;industrialData.data[k]=value*.98;industrialData.data[k+1]=value;industrialData.data[k+2]=value*.99;industrialData.data[k+3]=255;}
 industrialBrush.putImageData(industrialData,0,0);const industrialColor=new THREE.CanvasTexture(industrialCanvas);industrialColor.colorSpace=THREE.SRGBColorSpace;industrialColor.wrapS=industrialColor.wrapT=THREE.RepeatWrapping;industrialColor.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
 const skinCanvas=document.createElement('canvas');skinCanvas.width=skinCanvas.height=256;const skinBrush=skinCanvas.getContext('2d'),skinData=skinBrush.createImageData(256,256);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const fine=Math.sin(x*1.71+y*2.33)*Math.cos(y*1.93-x*.79),mottle=Math.sin(x*.071+Math.sin(y*.043)*2)*Math.cos(y*.089+Math.sin(x*.061)),freckle=Math.pow(Math.max(0,Math.sin(x*.41+y*.23)*Math.cos(y*.39-x*.12)),12),v=221+mottle*18+fine*5-freckle*42,k=(y*256+x)*4;skinData.data[k]=v;skinData.data[k+1]=v*.97;skinData.data[k+2]=v*.94;skinData.data[k+3]=255}skinBrush.putImageData(skinData,0,0);const skinColor=new THREE.CanvasTexture(skinCanvas);skinColor.colorSpace=THREE.SRGBColorSpace;skinColor.wrapS=skinColor.wrapT=THREE.RepeatWrapping;
 function geometry(faces){if(geoCache.has(faces)){const cached=geoCache.get(faces);cached.lastUsed=renderFrame;if(faces.dynamic&&(!(faces.alienMaterial||faces.capitalHull)||cached.uploadFrame!==renderFrame)){cached.uploadFrame=renderFrame;const a=cached.geometry.attributes.position;const positions=a.array;const bounds=cached.motionBounds;let minX=Infinity,minY=Infinity,minZ=Infinity,maxX=-Infinity,maxY=-Infinity,maxZ=-Infinity;for(let i=0;i<cached.sources.length;i++){const v=cached.sources[i],j=i*3;positions[j]=v[0];positions[j+1]=v[1];positions[j+2]=v[2];if(bounds){minX=Math.min(minX,v[0]);minY=Math.min(minY,v[1]);minZ=Math.min(minZ,v[2]);maxX=Math.max(maxX,v[0]);maxY=Math.max(maxY,v[1]);maxZ=Math.max(maxZ,v[2]);}}if(bounds){bounds.cx=(minX+maxX)/2;bounds.cy=(minY+maxY)/2;bounds.cz=(minZ+maxZ)/2;bounds.hx=(maxX-minX)/2;bounds.hy=(maxY-minY)/2;bounds.hz=(maxZ-minZ)/2;}a.needsUpdate=true;cached.normalFrame=(cached.normalFrame||0)+1;if(faces.painted===undefined&&cached.normalFrame%((window.flightEffectsQuality||1)<1?4:3)===0)smoothNormals(cached.geometry,cached.smoothGroups||[])}return cached}const sources=[],positions=[],colors=[],glow=[],flex=[],wet=[],textureWeight=[],blinkData=[],faunaJoints=[],uv=[],indices=[],lookup=new Map(),normalGroups=new Map();let organic=!!faces.skin;
 for(const f of faces){const ids=f.v.map((v,vi)=>{const key=v.map(n=>n.toFixed(4)).join(',')+'|'+f.c.join(',')+'|'+f.em+'|'+f.flex+'|'+(f.wet||0)+'|'+(f.textureWeight??1)+'|'+(f.blink||'')+'|'+(f.joint||'')+(f.uv?'|'+f.uv[vi].join(','):'');if(lookup.has(key))return lookup.get(key);const i=positions.length/3;positions.push(...v);sources.push(v);const normalKey=v.map(n=>n.toFixed(4)).join(',');if(!normalGroups.has(normalKey))normalGroups.set(normalKey,[]);normalGroups.get(normalKey).push(i);const color=new THREE.Color(`rgb(${f.c.map(n=>Math.round(Math.max(0,Math.min(255,n)))).join(',')})`);colors.push(color.r,color.g,color.b);glow.push(f.em||0);flex.push(f.flex||0);wet.push(f.wet||0);textureWeight.push(f.textureWeight??1);faunaJoints.push(...(f.joint||[0,0,0,0]));blinkData.push(...(f.blink?[f.blink[0],f.blink[1],1]:[0,0,0]));if(f.uv){uv.push(...f.uv[vi]);}else if(faces.rock)uv.push(v[0]/160,v[1]/160);else uv.push(v[0]/38,v[1]/38);lookup.set(key,i);return i});for(let i=1;i<ids.length-1;i++)indices.push(ids[0],ids[i],ids[i+1]);if(f.flex)organic=true}
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.setAttribute('glow',new THREE.Float32BufferAttribute(glow,1));g.setAttribute('flex',new THREE.Float32BufferAttribute(flex,1));g.setAttribute('wet',new THREE.Float32BufferAttribute(wet,1));g.setAttribute('textureWeight',new THREE.Float32BufferAttribute(textureWeight,1));g.setAttribute('blinkData',new THREE.Float32BufferAttribute(blinkData,3));g.setAttribute('faunaJoint',new THREE.Float32BufferAttribute(faunaJoints,4));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(indices);if(faces.dynamic)g.attributes.position.setUsage(THREE.DynamicDrawUsage);const smoothGroups=faces.alienMaterial?[...normalGroups.values()].filter(g=>g.length>1):[];smoothNormals(g,smoothGroups);if(faces.dynamic)g.attributes.normal.setUsage(THREE.DynamicDrawUsage);g.computeBoundingSphere();if(organic||faces.fauna)g.boundingSphere.radius+=90;const value={geometry:g,organic,sources,smoothGroups,lastUsed:renderFrame};if(faces.cpuBounds){g.computeBoundingBox();const lo=g.boundingBox.min,hi=g.boundingBox.max;value.motionBounds={cx:(lo.x+hi.x)/2,cy:(lo.y+hi.y)/2,cz:(lo.z+hi.z)/2,hx:(hi.x-lo.x)/2,hy:(hi.y-lo.y)/2,hz:(hi.z-lo.z)/2};}geoCache.set(faces,value);return value}
 function material(organic){const m=new THREE.MeshStandardMaterial({vertexColors:true,metalness:organic?0:.64,roughness:organic?.76:.34,map:organic?skinColor:null,side:THREE.DoubleSide,bumpMap:organic?skinTexture:metalTexture,bumpScale:organic?1.1:.3,transparent:true,forceSinglePass:true});
 // A draw hook runs before Three compiles a newly selected program. Keep
 // uniforms on the material itself so first-frame and cached variants read
 // the same current state, instead of whichever shader compiled most recently.
 const modelUniforms=m.userData.modelUniforms={motionTime:{value:0},rigKind:{value:0},hitFlash:{value:0},organicSurface:{value:organic?1:0},alienSurface:{value:0}};
 m.onBeforeCompile=shader=>{Object.assign(shader.uniforms,modelUniforms);m.userData.shader=shader;
 shader.vertexShader='attribute vec4 faunaJoint; attribute vec3 blinkData; float blinkPulse(float x){return x<0.0||x>.26?0.0:x<.065?sin(x/.065*1.57079633):cos((x-.065)/.195*1.57079633);} attribute float textureWeight; varying float vTextureWeight; attribute float glow; attribute float flex; attribute float wet; varying float vWet; varying vec3 vSkinPosition; varying float vGlow; uniform float motionTime; uniform float rigKind;\n'+shader.vertexShader;
 shader.vertexShader=`
 vec3 speciesJoint(vec3 p,vec4 j,float t){
  if(j.w<.5)return p;vec3 v=p-j.xyz;float side=j.z<0.0?-1.0:1.0;float w=min(1.0,length(v)/35.0),a=0.0;int axis=0;
  if(j.w<1.5||(j.w>2.5&&j.w<3.5)||j.w>7.5){axis=1;a=j.w>7.5?t*18.0:side*sin(t*(j.w<1.5?14.0:5.0)+j.x*.03)*(j.w<1.5?.62:.38);}
  else if(j.w>3.5&&j.w<4.5){axis=2;a=sin(t*6.0-max(0.0,v.x)*.045)*min(1.0,max(0.0,v.x)/85.0)*.27;}
  else if(j.w>4.5&&j.w<5.5){float pulse=pow((1.0+cos(t*4.8))*.5,4.0),f=min(1.0,abs(v.x)/45.0);return j.xyz+vec3(v.x+3.0*pulse*f,v.yz*(1.0-.14*pulse*f));}
  else if(j.w>5.5&&j.w<6.5)a=.08+pow((1.0+sin(t*3.0))*.5,3.0)*.32;
  else if(j.w>6.5){axis=2;float u=clamp((length(v)-12.0)/23.0,0.0,1.0),bend=u*u*(3.0-2.0*u);if(bend==0.0)return p;a=sin(t*9.0-bend*3.0+j.x*.09+j.z*.07)*bend*.34;}
  else a=sin(t*9.0+j.x*.09+j.z*.07)*w*.28;
  mat2 turn=mat2(cos(a),sin(a),-sin(a),cos(a));
  if(axis==1)v.yz=turn*v.yz;else if(axis==2)v.xz=turn*v.xz;else v.xy=turn*v.xy;return j.xyz+v;
 }
 `+shader.vertexShader;
 shader.vertexShader=shader.vertexShader.replace('#include <beginnormal_vertex>',`#include <beginnormal_vertex>
 if(faunaJoint.w>.5)objectNormal=normalize(speciesJoint(position+objectNormal*.01,faunaJoint,motionTime)-speciesJoint(position,faunaJoint,motionTime));
 `);
 shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>
 if(blinkData.z>.5){float t=mod(motionTime*1.55+blinkData.y*1.73,17.3);float b=max(max(blinkPulse(t-2.1),blinkPulse(t-6.7)),max(max(blinkPulse(t-10.2),blinkPulse(t-10.57)),blinkPulse(t-15.4)));transformed.y=blinkData.x+(transformed.y-blinkData.x)*(1.0-.97*b);}
 vTextureWeight=textureWeight;vGlow=glow;vWet=wet;vSkinPosition=position;
 if(faunaJoint.w>.5)transformed=speciesJoint(transformed,faunaJoint,motionTime);
 else if(rigKind>2.5){float span=max(0.0,abs(position.y)-12.0);float drive=1.0+.65*pow((1.0+cos(motionTime*3.2))*.5,5.0);transformed.z+=sin(motionTime*3.2-position.x*.055)*span*.44*drive;}
 else if(rigKind>0.5){float phase=motionTime*(rigKind<1.5?4.8:3.8);
 if(position.x<23.0){float weight=smoothstep(-22.0,-4.0,position.x)*(1.0-smoothstep(10.0,23.0,position.x));float contraction=pow((1.0+cos(phase+(position.x+20.0)*.045))*.5,4.0);float extension=pow((1.0+cos(phase-.3))*.5,5.0)*(1.0-smoothstep(4.0,23.0,position.x));transformed.x+=weight*contraction*4.0-extension*9.0;transformed.yz*=(1.0-.22*weight*contraction)*(1.0-extension*.045);}
 else{float along=max(0.0,position.x-23.0)/67.0;float arm=atan(position.z,position.y);float lag=phase-along*3.5+arm*.18;float cycle=mod(mod(motionTime,3.6)+3.6,3.6);float tuck=smoothstep(.35,.6,cycle)*(1.0-smoothstep(1.35,1.8,cycle));float root=smoothstep(0.0,.4,along);float jet=pow((1.0+cos(phase))*.5,5.0);float release=sin(lag-.65)+.32*sin(2.0*lag-1.3);float bundle=(1.0+root*(-.46*pow((1.0+cos(lag))*.5,3.0)+.20*max(0.0,sin(lag-.7))+(1.0-tuck)*.30))*(1.0-.75*tuck*root);float drive=1.0+jet*.7;float curl=release*along*along*32.0*drive*(1.0-.9*tuck);transformed.x+=root*along*(jet*9.0-max(0.0,release)*24.0);transformed.y=position.y*bundle+cos(arm+.8+root*.48*sin(phase-along*1.8)+tuck*along*3.0)*curl;transformed.z=position.z*bundle+sin(arm+.8+root*.48*sin(phase-along*1.8)+tuck*along*3.0)*curl;}}
 else if(flex>0.0){float cycle=mod(mod(motionTime,3.6)+3.6,3.6);float tuck=smoothstep(.35,.6,cycle)*(1.0-smoothstep(1.35,1.8,cycle));float root=clamp((position.x-10.0)/45.0,0.0,1.0);transformed.yz*=1.0-.75*tuck*root;float drive=1.0+.75*pow((1.0+cos(motionTime*2.0))*.5,5.0);float bend=max(0.0,position.x-10.0)*flex*drive*(1.0-.9*tuck);transformed.y+=sin(motionTime*3.0-position.x*.07)*bend*.23;transformed.z+=cos(motionTime*2.4-position.x*.06)*bend*.22;}`);
 shader.fragmentShader=`varying float vTextureWeight; varying float vGlow; varying float vWet; varying vec3 vSkinPosition; uniform float alienSurface; uniform float hitFlash; uniform float organicSurface;
 float skinHash(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}
 float skinNoise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(mix(skinHash(i),skinHash(i+vec3(1,0,0)),f.x),mix(skinHash(i+vec3(0,1,0)),skinHash(i+vec3(1,1,0)),f.x),f.y),mix(mix(skinHash(i+vec3(0,0,1)),skinHash(i+vec3(1,0,1)),f.x),mix(skinHash(i+vec3(0,1,1)),skinHash(i+vec3(1,1,1)),f.x),f.y),f.z);}
 `+shader.fragmentShader;
 shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>', '#include <map_fragment>\n if(alienSurface>0.5){float relief=dot(diffuseColor.rgb,vec3(.2126,.7152,.0722));diffuseColor.rgb=mix(vec3(1.0),vec3(clamp(.32+relief*2.9,.28,1.35)),vTextureWeight);}');
 shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
 if(alienSurface>0.5){float dermalPatch=skinNoise(vSkinPosition*.075);float pore=skinNoise(vSkinPosition*1.3);float fold=skinNoise(vSkinPosition*.38);float vein=1.0-smoothstep(.012,.05,abs(fold-.48));vec3 pigment=mix(vec3(.56,.70,.87),vec3(1.20,1.05,.78),smoothstep(.23,.76,dermalPatch));float scaleEdge=1.0-smoothstep(.06,.18,abs(sin(vSkinPosition.x*.72+sin(vSkinPosition.y*.9)*.7)*sin(vSkinPosition.z*.72+sin(vSkinPosition.y*.65)*.6)));pigment*=.83+pore*.25-vein*.12-scaleEdge*(alienSurface<1.5?.18:.07);diffuseColor.rgb*=mix(vec3(1.0),pigment,vTextureWeight*(1.0-vWet*.8));}else if(organicSurface>1.5){float strata=skinNoise(vSkinPosition*.12)+skinNoise(vSkinPosition*.6)*.3;float mineral=dot(diffuseColor.rgb,vec3(.2126,.7152,.0722));diffuseColor.rgb=mix(diffuseColor.rgb,vec3(mineral*.98,mineral,mineral*1.03),.7)*(.7+strata*.5);}else if(organicSurface>0.5){float skinPatch=skinNoise(vSkinPosition*.085);float detail=skinNoise(vSkinPosition*.48);float vein=1.0-smoothstep(.015,.075,abs(detail-.49));vec3 dermis=mix(vec3(.48,.39,.43),vec3(1.14,1.08,.86),smoothstep(.2,.78,skinPatch));dermis*=1.0-vein*.3;dermis*=.83+skinNoise(vSkinPosition*1.4)*.3;diffuseColor.rgb*=mix(dermis,vec3(1.0),vWet);}else{float wear=skinNoise(vSkinPosition*.7);float panel=step(.94,fract(vSkinPosition.x*.09))+step(.94,fract(vSkinPosition.y*.09));diffuseColor.rgb*=clamp(.7+wear*.4-panel*.25,.3,1.1);}
 `);
 shader.fragmentShader=shader.fragmentShader.replace('#include <roughnessmap_fragment>',`#include <roughnessmap_fragment>
 if(alienSurface>0.5)roughnessFactor=mix((alienSurface<1.5?.58:.49)+skinNoise(vSkinPosition*.24)*.18,.17,vWet);else if(organicSurface>0.5)roughnessFactor=mix(.68+skinNoise(vSkinPosition*.2)*.2,.13,vWet);
 `);
 shader.fragmentShader=shader.fragmentShader.replace('#include <emissivemap_fragment>','#include <emissivemap_fragment>\n totalEmissiveRadiance += vGlow * diffuseColor.rgb * 1.8;');
 shader.fragmentShader=shader.fragmentShader.replace('#include <opaque_fragment>',`
 // Brief impact sheen preserves albedo, skin pores and light/shadow contrast.
 // A glancing surface catches the flash; the whole creature never becomes a
 // flat white mask while sustained automatic fire keeps registering hits.
 float impactRim=pow(1.0-clamp(abs(dot(normal,normalize(vViewPosition))),0.0,1.0),3.0);
 outgoingLight*=1.0+hitFlash*.10;
 outgoingLight+=hitFlash*impactRim*(vec3(.12,.19,.21)+diffuseColor.rgb*.16);
 #include <opaque_fragment>`);};return m}
 const affine=new THREE.Matrix4(),local=new THREE.Matrix4(),rotation=new THREE.Matrix4(),scaleMatrix=new THREE.Matrix4(),euler=new THREE.Euler(0,0,0,'ZXY');
 const instanceGroups=new Map(),instanceMatrix=new THREE.Matrix4();let frameInstancedObjects=0;
 function queueRigidInstance(faces,data,context,x,y,scale,yaw,roll,pitch){
  const a=context.getTransform();if(a.a*a.d-a.b*a.c<0||scale<0)return false; // Three instancing does not support reflected matrices.
  let group=instanceGroups.get(faces);
  if(!group){const object=new THREE.InstancedMesh(data.geometry,material(false),128);object.instanceMatrix.setUsage(THREE.DynamicDrawUsage);object.frustumCulled=false;object.matrixAutoUpdate=false;object.visible=false;scene.add(object);group={object,count:0};instanceGroups.set(faces,group);}
  if(group.count===128)return false; // Overflow keeps the ordinary draw path.
  if(group.object.geometry!==data.geometry)group.object.geometry=data.geometry;
  const pr=window.flightRenderScale||1,zScale=Math.sqrt(Math.abs(a.a*a.d-a.b*a.c))/pr;
  affine.set(a.a/pr,a.c/pr,0,a.e/pr-720,-a.b/pr,-a.d/pr,0,380-a.f/pr,0,0,-zScale,0,0,0,0,1);local.makeTranslation(x,y,0);euler.set(roll,yaw,pitch,'ZXY');rotation.makeRotationFromEuler(euler);scaleMatrix.makeScale(scale,scale,scale);instanceMatrix.copy(affine).multiply(local).multiply(rotation).multiply(scaleMatrix);
  if(!includeDrawBounds(data,faces,instanceMatrix))return true;
  group.object.setMatrixAt(group.count++,instanceMatrix);group.object.count=group.count;group.object.renderOrder=batch;group.object.visible=true;group.object.instanceMatrix.needsUpdate=true;frameInstancedObjects++;pending++;return true;
 }
 function resetInstances(){for(const group of instanceGroups.values()){group.count=0;group.object.count=0;group.object.visible=false;}}
 const authored=new AuthoredAssets(scene);
 await authored.load();
 window.authoredModels=authored;
 function drawAuthored(faces,context,x,y,scale,yaw,roll,pitch,age,hit){
  if(!faces.authoredAsset||!authored.assets.has(faces.authoredAsset))return false;
  const a=context.getTransform(),pr=window.flightRenderScale||1,zScale=Math.sqrt(Math.abs(a.a*a.d-a.b*a.c))/pr;
  affine.set(a.a/pr,a.c/pr,0,a.e/pr-720,-a.b/pr,-a.d/pr,0,380-a.f/pr,0,0,-zScale,0,0,0,0,1);
  local.makeTranslation(x,y,0);euler.set(roll,yaw,pitch,'ZXY');rotation.makeRotationFromEuler(euler);scaleMatrix.makeScale(scale,scale,scale);
  instanceMatrix.copy(affine).multiply(local).multiply(rotation).multiply(scaleMatrix);
  const bounds={geometry:{boundingSphere:{center:authoredCenter,radius:AUTHORED_ASSETS[faces.authoredAsset].radius}}};
  if(!includeDrawBounds(bounds,{},instanceMatrix))return true;
  const item=authored.acquire(faces.authoredAsset,age,context.globalAlpha,hit,batch);
  item.root.matrix.copy(instanceMatrix);authored.submit(item);pending++;return true;
 }
 const authoredCenter=new THREE.Vector3();
 let pixelRatio=1;
 window.gpuModels={modelRadius(faces){if(AUTHORED_ASSETS[faces.authoredAsset])return AUTHORED_ASSETS[faces.authoredAsset].radius;const sphere=geometry(faces).geometry.boundingSphere;return sphere.center.length()+sphere.radius;},prepare(faces){for(const f of faces)if(f&&!authored.assets?.has(f.authoredAsset))geometry(f);},begin(){authored.begin();authored.trim();renderFrame++;if(renderFrame%120===0){for(const [faces,data] of geoCache){if(renderFrame-data.lastUsed>600){data.geometry.dispose();geoCache.delete(faces);disposedGeometry++;}}}const ratio=window.flightRenderScale||1;if(Math.abs(ratio-pixelRatio)>.02){pixelRatio=ratio;renderer.setPixelRatio(ratio);}used=0;batch=0;pending=0;pendingStart=0;frameDrawCalls=frameTriangles=frameCompositePixels=framePasses=0;resetClip();resetInstances();frameInstancedObjects=0;for(const s of slots)s.object.visible=false},draw(faces,context,x,y,scale,yaw,roll,pitch,age,hit,rig){if(drawAuthored(faces,context,x,y,scale,yaw,roll,pitch,age,hit))return;const data=geometry(faces);if(faces.instanceSafe&&!rig&&!hit&&context.globalAlpha>=.999&&queueRigidInstance(faces,data,context,x,y,scale,yaw,roll,pitch))return;let s=slots[used];if(!s){const normalMaterial=material(data.organic);s={object:new THREE.Mesh(data.geometry,normalMaterial),normalMaterial,faces};s.object.matrixAutoUpdate=false;s.object.frustumCulled=false;scene.add(s.object);slots.push(s);s.object.onBeforeRender=()=>{const u=s.object.material.userData.modelUniforms;if(u){u.organicSurface.value=s.surfaceKind;u.alienSurface.value=s.alienKind||0;u.motionTime.value=s.age;u.rigKind.value=s.rig==='squid'?1:s.rig==='octopus'?2:s.rig==='ray'?3:0;u.hitFlash.value=s.hit>0&&(s.age%.12)<.022?Math.sin((s.age%.12)/.022*Math.PI):0}};}if(s.object.geometry!==data.geometry){s.object.geometry=data.geometry;}s.faces=faces;s.object.frustumCulled=!faces.dynamic;
 // A pooled slot can change from terrain to a creature or atlas every frame.
 // Select its material first, then reset every surface property by texture identity.
 const organic=data.organic||rig==='squid'||rig==='octopus';s.surfaceKind=faces.rock?2:organic?1:0;s.alienKind=faces.alienMaterial==='chitin'?1:faces.alienMaterial==='flesh'?2:0;
 if(faces.painted!==undefined){if(!bossAtlasTexture){bossAtlasTexture=new THREE.TextureLoader().load('assets/boss-atlas-v2.png');bossAtlasTexture.colorSpace=THREE.SRGBColorSpace;bossAtlasTexture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());}if(!s.paintMaterial)s.paintMaterial=new THREE.MeshBasicMaterial({map:bossAtlasTexture,transparent:true,alphaTest:.04,side:THREE.DoubleSide,toneMapped:false});s.object.material=s.paintMaterial;s.paintMaterial.color.setRGB(hit>0?1.2:1,hit>0?1.2:1,hit>0?1.2:1);}
 else{const m=s.normalMaterial;s.object.material=m;const map=faces.alienMaterial?alienTextures[faces.alienMaterial]:faces.rock?rockTexture:organic?skinColor:faces.industrial?industrialColor:null,bump=faces.alienMaterial?alienTextures[faces.alienMaterial]:faces.rock?rockTexture:organic?skinTexture:faces.capitalSurface?industrialColor:metalTexture;if(m.map!==map||m.bumpMap!==bump){const programChanged=!!m.map!==!!map||!!m.bumpMap!==!!bump;m.map=map;m.bumpMap=bump;if(programChanged)m.needsUpdate=true;}m.metalness=faces.rock||organic?0:faces.capitalSurface?.58:faces.industrial?.3:.64;m.roughness=faces.rock?.98:faces.alienMaterial==='chitin'?.53:organic?.76:faces.capitalSurface?.46:faces.industrial?.8:.34;m.bumpScale=faces.alienMaterial==='chitin'?.95:faces.alienMaterial==='flesh'?.23:faces.rock?1.7:organic?1.1:.3;}
 const a=context.getTransform(),pr=window.flightRenderScale||1,zScale=Math.sqrt(Math.abs(a.a*a.d-a.b*a.c))/pr;affine.set(a.a/pr,a.c/pr,0,a.e/pr-720,-a.b/pr,-a.d/pr,0,380-a.f/pr,0,0,-zScale,0,0,0,0,1);local.makeTranslation(x,y,0);euler.set(roll,yaw,pitch,'ZXY');rotation.makeRotationFromEuler(euler);scaleMatrix.makeScale(scale,scale,scale);s.object.matrix.copy(affine).multiply(local).multiply(rotation).multiply(scaleMatrix);s.object.visible=includeDrawBounds(data,faces,s.object.matrix);s.object.material.opacity=context.globalAlpha;s.object.material.depthWrite=faces.painted===undefined&&context.globalAlpha>.96;s.object.renderOrder=batch;s.age=age;s.hit=hit;s.rig=rig;
 used++;if(s.object.visible)pending++},flush(context){if(!pending){pendingStart=used;return;}pending=0;const width=clipRight-clipLeft,height=clipBottom-clipTop;renderer.setScissor(clipLeft,760-clipBottom,width,height);renderer.setScissorTest(true);renderer.render(scene,camera);renderer.setScissorTest(false);framePasses++;frameCompositePixels+=width*height;frameDrawCalls+=renderer.info.render.calls;frameTriangles+=renderer.info.render.triangles;peakTriangles=Math.max(peakTriangles,frameTriangles);context.save();context.setTransform(1,0,0,1,0,0);context.globalAlpha=1;context.globalCompositeOperation='source-over';context.drawImage(surface,clipLeft*surface.width/1440,clipTop*surface.height/760,width*surface.width/1440,height*surface.height/760,clipLeft*context.canvas.width/1440,clipTop*context.canvas.height/760,width*context.canvas.width/1440,height*context.canvas.height/760);context.restore();for(let i=pendingStart;i<used;i++)slots[i].object.visible=false;pendingStart=used;authored.flush();resetClip();resetInstances();batch++;frames++},stats(){return{authored:authored.stats(),engine:'Three.js',version:THREE.REVISION,webgl:true,drawCalls:frameDrawCalls,triangles:frameTriangles,instancedObjects:frameInstancedObjects,instanceGroups:instanceGroups.size,compositePasses:framePasses,compositePixels:frameCompositePixels,compositeCoverage:framePasses?+(frameCompositePixels/(framePasses*1440*760)).toFixed(3):0,pooledObjects:slots.length,peakTriangles,frames,renderFrames:renderFrame,geometryCache:geoCache.size,disposedGeometry,gpuGeometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,shaderPrograms:renderer.info.programs?.length||0}}};
}
// Fetch together, execute classic scripts in dependency order.
if(!document.documentElement.hasAttribute('data-model-gallery'))await Promise.all(['audio.js','models.js','boss-creatures.js','boss-machines.js','capital-ship.js','levels.js','runs.js','art.js','tide-encounter.js','game.js'].map(src=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.async=false;s.src=src+new URL(import.meta.url).search;s.onload=resolve;s.onerror=reject;document.body.append(s)})));
